include file("/etc/cortex/secret.conf")

http.address = 0.0.0.0
http.port = 9001

play.http.secret.key = "CortexTestPassword"

search {
  index = cortex
  uri = "http://elasticsearch:9200"
}

storage {
  provider = localfs
  localfs.location = /tmp/cortex-jobs
}

job {
  runner = [docker]
}

docker {
  job {
    directory = /tmp/cortex-jobs
  }
}

analyzer {
  urls = [
    "https://download.thehive-project.org/analyzers.json"
  ]
}
