include file("/etc/thehive/secret.conf")

http.address = 0.0.0.0
http.port = 9000

play.http.secret.key = "ThHiv3App"

scalligraph {
  database {
    provider = janusgraph
    janusgraph {
      storage {
        backend = cql
        hostname = ["cassandra"]
        cql {
          cluster-name = thp
          keyspace = thehive
        }
      }
      index.search {
        backend = elasticsearch
        hostname = ["elasticsearch"]
        index-name = thehive
      }
    }
  }
}

storage {
  provider = localfs
  localfs.location = /opt/thp/thehive/data
}

play.modules.enabled += org.thp.thehive.connector.cortex.CortexModule
cortex {
  servers = [
    {
      name = local
      url = "http://cortex:9001"
      auth {
        type = "bearer"
        key = "cortex-api-key"
      }
    }
  ]
}
